services:
  mysql:
    container_name: "bd-pkm"
    image: mysql:latest
    #network_mode: "host" ##para criar o container com o mesmo IP
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123@123
      MYSQL_DATABASE: padrao
      MYSQL_USER: pokemon
      MYSQL_PASSWORD: 123@123
    volumes:
      - ./vol_bd:/var/lib/mysql
      # Mapeamento do tipo BIND MOUNT
      #- /home/docker/app/docvolumes/vol_bd:/var/lib/mysql
      # com volume tipo VOLUME
      # - vol_bd_new:/var/lib/mysql
    # networks:
    #   - exist

  pyapp:
    container_name: pyapp
    ports:
      - "8689:8689"
    build:
      context: .
      dockerfile: dockerfile
    extra_hosts:
      bd-pkm: 172.26.231.208
    # networks:
    #   - exist
    depends_on:
      - mysql

  apimon:
    container_name: apimon
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: dockerobs

#Caso queira utilizar um volume do tipo VOLUME
#volumes:
#  vol_bd_new:
#  name: bd_volume_mysql
#  external: true #caso queria usar um volume criado anteriormente

# networks:
#   devops_rede:
#     driver: bridge
#     name: devops_rede
