services:
  jaegger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411" 