name: Pipeline

on:
    [workflow_dispatch]

jobs:
  checkout_code:
    name: Terraformando Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
